// Trigger reload
export const TRIGGER_RELOAD = "TRIGGER_RELOAD";

// User
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

// Product
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

// Store
export const STORE_LIST_REQUEST = "STORE_LIST_REQUEST";
export const STORE_LIST_SUCCESS = "STORE_LIST_SUCCESS";
export const STORE_LIST_FAIL = "STORE_LIST_FAIL";
export const CREATE_STORE_REQUEST = "CREATE_STORE_REQUEST";
export const CREATE_STORE_SUCCESS = "CREATE_STORE_SUCCESS";
export const CREATE_STORE_FAIL = "CREATE_STORE_FAIL";
export const DELETE_STORE_REQUEST = "DELETE_STORE_REQUEST";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";
export const DELETE_STORE_FAIL = "DELETE_STORE_FAIL";
export const VIEW_DETAIL_STORE_REQUEST = "VIEW_DETAIL_STORE_REQUEST";
export const VIEW_DETAIL_STORE_SUCCESS = "VIEW_DETAIL_STORE_SUCCESS";
export const VIEW_DETAIL_STORE_FAIL = "VIEW_DETAIL_STORE_FAIL";
export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAIL = "UPDATE_STORE_FAIL";

// Size
export const SIZE_LIST_REQUEST = "SIZE_LIST_REQUEST";
export const SIZE_LIST_SUCCESS = "SIZE_LIST_SUCCESS";
export const SIZE_LIST_FAIL = "SIZE_LIST_FAIL";
export const CREATE_SIZE_REQUEST = "CREATE_SIZE_REQUEST";
export const CREATE_SIZE_SUCCESS = "CREATE_SIZE_SUCCESS";
export const CREATE_SIZE_FAIL = "CREATE_SIZE_FAIL";
export const DELETE_SIZE_REQUEST = "DELETE_SIZE_REQUEST";
export const DELETE_SIZE_SUCCESS = "DELETE_SIZE_SUCCESS";
export const DELETE_SIZE_FAIL = "DELETE_SIZE_FAIL";
export const VIEW_DETAIL_SIZE_REQUEST = "VIEW_DETAIL_SIZE_REQUEST";
export const VIEW_DETAIL_SIZE_SUCCESS = "VIEW_DETAIL_SIZE_SUCCESS";
export const VIEW_DETAIL_SIZE_FAIL = "VIEW_DETAIL_SIZE_FAIL";
export const UPDATE_SIZE_REQUEST = "UPDATE_SIZE_REQUEST";
export const UPDATE_SIZE_SUCCESS = "UPDATE_SIZE_SUCCESS";
export const UPDATE_SIZE_FAIL = "UPDATE_SIZE_FAIL";

// Color
export const COLOR_LIST_REQUEST = "COLOR_LIST_REQUEST";
export const COLOR_LIST_SUCCESS = "COLOR_LIST_SUCCESS";
export const COLOR_LIST_FAIL = "COLOR_LIST_FAIL";
export const COLOR_LIST_ALL_SUCCESS = "COLOR_LIST_ALL_SUCCESS";
export const CREATE_COLOR_REQUEST = "CREATE_COLOR_REQUEST";
export const CREATE_COLOR_SUCCESS = "CREATE_COLOR_SUCCESS";
export const CREATE_COLOR_FAIL = "CREATE_COLOR_FAIL";
export const DELETE_COLOR_REQUEST = "DELETE_COLOR_REQUEST";
export const DELETE_COLOR_SUCCESS = "DELETE_COLOR_SUCCESS";
export const DELETE_COLOR_FAIL = "DELETE_COLOR_FAIL";
export const VIEW_DETAIL_COLOR_REQUEST = "VIEW_DETAIL_COLOR_REQUEST";
export const VIEW_DETAIL_COLOR_SUCCESS = "VIEW_DETAIL_COLOR_SUCCESS";
export const VIEW_DETAIL_COLOR_FAIL = "VIEW_DETAIL_COLOR_FAIL";
export const UPDATE_COLOR_REQUEST = "UPDATE_COLOR_REQUEST";
export const UPDATE_COLOR_SUCCESS = "UPDATE_COLOR_SUCCESS";
export const UPDATE_COLOR_FAIL = "UPDATE_COLOR_FAIL";

// Category
export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";
export const CATEGORY_LIST_ALL_SUCCESS = "CATEGORY_LIST_ALL_SUCCESS";
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";
export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";
export const VIEW_DETAIL_CATEGORY_REQUEST = "VIEW_DETAIL_CATEGORY_REQUEST";
export const VIEW_DETAIL_CATEGORY_SUCCESS = "VIEW_DETAIL_CATEGORY_SUCCESS";
export const VIEW_DETAIL_CATEGORY_FAIL = "VIEW_DETAIL_STORECATEGORY_FAIL";

// Promotion
export const PROMOTION_LIST_REQUEST = "PROMOTION_LIST_REQUEST";
export const PROMOTION_LIST_SUCCESS = "PROMOTION_LIST_SUCCESS";
export const PROMOTION_LIST_FAIL = "PROMOTION_LIST_FAIL";
export const CREATE_PROMOTION_REQUEST = "CREATE_PROMOTION_REQUEST";
export const CREATE_PROMOTION_SUCCESS = "CREATE_PROMOTION_SUCCESS";
export const CREATE_PROMOTION_FAIL = "CREATE_PROMOTION_FAIL";
export const DELETE_PROMOTION_REQUEST = "DELETE_PROMOTION_REQUEST";
export const DELETE_PROMOTION_SUCCESS = "DELETE_PROMOTION_SUCCESS";
export const DELETE_PROMOTION_FAIL = "DELETE_PROMOTION_FAIL";
export const VIEW_DETAIL_PROMOTION_REQUEST = "VIEW_DETAIL_PROMOTION_REQUEST";
export const VIEW_DETAIL_PROMOTION_SUCCESS = "VIEW_DETAIL_PROMOTION_SUCCESS";
export const VIEW_DETAIL_PROMOTION_FAIL = "VIEW_DETAIL_PROMOTION_FAIL";
export const UPDATE_PROMOTION_REQUEST = "UPDATE_PROMOTION_REQUEST";
export const UPDATE_PROMOTION_SUCCESS = "UPDATE_PROMOTION_SUCCESS";
export const UPDATE_PROMOTION_FAIL = "UPDATE_PROMOTION_FAIL";

// Manager
export const MANAGER_LIST_REQUEST = "MANAGER_LIST_REQUEST";
export const MANAGER_LIST_SUCCESS = "MANAGER_LIST_SUCCESS";
export const MANAGER_LIST_FAIL = "MANAGER_LIST_FAIL";

export const STAFF_LIST_REQUEST = "STAFF_LIST_REQUEST";
export const STAFF_LIST_SUCCESS = "STAFF_LIST_SUCCESS";
export const STAFF_LIST_FAIL = "STAFF_LIST_FAIL";

export const CUSTOMER_LIST_REQUEST = "CUSTOMER_LIST_REQUEST";
export const CUSTOMER_LIST_SUCCESS = "CUSTOMER_LIST_SUCCESS";
export const CUSTOMER_LIST_FAIL = "CUSTOMER_LIST_FAIL";
