// Trigger reload
export const TRIGGER_RELOAD = "TRIGGER_RELOAD";

// User
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

// Product
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

// Size
export const SIZE_LIST_REQUEST = "SIZE_LIST_REQUEST";
export const SIZE_LIST_SUCCESS = "SIZE_LIST_SUCCESS";
export const SIZE_LIST_FAIL = "SIZE_LIST_FAIL";

// Color
export const COLOR_LIST_REQUEST = "COLOR_LIST_REQUEST";
export const COLOR_LIST_SUCCESS = "COLOR_LIST_SUCCESS";
export const COLOR_LIST_FAIL = "COLOR_LIST_FAIL";

// Category
export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";
